name: Connected
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # bottom_navy_bar: ^5.4.0
  line_awesome_icons: ^1.0.4+2
  google_fonts: ^1.1.0
  store_redirect: ^1.0.2
  # ff_navigation_bar: ^0.1.5
  # titled_navigation_bar: ^4.1.0
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  file_picker: ^1.13.2
  firebase_storage: ^3.1.6
  uuid: ^2.2.0
  google_sign_in: ^4.5.1
  # dynamic_theme: ^1.0.0
  # modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.8
  hive: ^1.4.2
  hive_flutter: ^0.3.1
  path_provider: ^1.6.11
  # flutter_phoenix: ^0.1.0
  # persistent_bottom_nav_bar: ^2.0.5
  dio: ^3.0.9
  permission_handler: ^5.0.1+1
  # url_launcher: ^5.5.0
  line_awesome_flutter: ^1.0.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
